
// ---------------------------------------------------------------
// List of advertising partners from the GDPR consent dialogue boxx
// from a visit to dailymail.co.uk on 11th July 2020.
// Companies that are listed twice, perhaps because they are operating in
// different territories, have been edited to a single entry.
//
// 13 Jul 2020
// ---------------------------------------------------------------

var partners = [
': Tappx' ,
'1020, Inc. dba Placecast and Ericsson Emodo' ,
'1plusX AG' ,
'2KDirect, Inc. (dba iPromote)' ,
'33Across' ,
'7Hops.com Inc. (ZergNet)' ,
'A Million Ads Ltd.' ,
'A.Mob' ,
'AAX LLC' ,
'Accelerize Inc.' ,
'Accorp Sp. z o.o.' ,
'Active Agent AG' ,
'Acuityads Inc.' ,
'Ad Unity Ltd.' ,
'ad6media' ,
'Adacado Technologies Inc. (DBA Adacado)' ,
'adality GmbH' ,
'ADARA MEDIA UNLIMITED' ,
'AdClear GmbH' ,
'AdColony, Inc.' ,
'AddApptr GmbH' ,
'AdDefend GmbH' ,
'AdElement Media Solutions Pvt Ltd.' ,
'Adello Group AG' ,
'Adelphic LLC' ,
'Adevinta Spain S.L.U.' ,
'Adform A/S' ,
'Adhese' ,
'adhood.com' ,
'Adikteev / Emoteev' ,
'Adimo' ,
'ADITION technologies AG' ,
'Adkernel LLC' ,
'Adledge' ,
'Adloox SA' ,
'Adludio Ltd.' ,
'ADMAN - Phaistos Networks, S.A.' ,
'ADman Interactive SL' ,
'adMarketplace, Inc.' ,
'AdMaxim Inc.' ,
'Admedo Ltd.' ,
'admetrics GmbH' ,
'Admixer EU GmbH' ,
'Admotion SRL' ,
'Adnami Aps' ,
'Adobe Advertising Cloud' ,
'Adobe Audience Manager' ,
'Adprime Media Inc.' ,
'ADRINO Sp. z o.o.' ,
'adrule mobile GmbH' ,
'Adserve.zone / Artworx AS' ,
'Adsolutions BV' ,
'AdSpirit GmbH' ,
'adsquare GmbH' ,
'Adssets AB' ,
'AdsWizz Inc.' ,
'Adtelligent Inc.' ,
'AdTheorent, Inc.' ,
'AdTiming Technology Company Limited' ,
'ADUX' ,
'advanced store GmbH' ,
'ADventori SAS' ,
'Adverline' ,
'ADWAYS SAS' ,
'ADYOULIKE SA' ,
'Aerserv LLC' ,
'Affectv Ltd.' ,
'affilinet' ,
'Affle International' ,
'Alive & Kicking Global Limited' ,
'Alliance Gravity Data Media' ,
'Amobee, Inc.' ,
'AntVoice' ,
'Apester Ltd.' ,
'AppConsent Xchange' ,
'Appier PTE Ltd.' ,
'AppNexus Inc.' ,
'Arcspire Limited' ,
'Arkeero' ,
'ARMIS SAS' ,
'Arrivalist Co.' ,
'ATG Ad Tech Group GmbH' ,
'Audience Network' ,
'Audience Trading Platform Ltd.' ,
'AudienceProject Aps' ,
'Audiens S.r.l.' ,
'AuDigent' ,
'audio content & control GmbH' ,
'Automattic Inc.' ,
'Avazu Inc.' ,
'Avid Media Ltd.' ,
'Avocet Systems Limited' ,
'Axel Springer Teaser Ad GmbH' ,
'Axonix Ltd.' ,
'Azerion Holding B.V.' ,
'B2B Media Group EMEA GmbH' ,
'Bandsintown Amplified LLC' ,
'Bannerflow AB' ,
'Beachfront Media LLC' ,
'Beaconspark Ltd.' ,
'Beemray Oy' ,
'BeeswaxIO Corporation' ,
'BEINTOO SPA' ,
'BeOp' ,
'Better Banners A/S' ,
'Between Exchange' ,
'BidBerry SRL' ,
'Bidmanagement GmbH' ,
'Bidstack Limited' ,
'BIDSWITCH GmbH' ,
'Bidtellect, Inc.' ,
'BidTheatre AB' ,
'Bigabid Media Ltd.' ,
'BILENDI SA' ,
'Bit Q Holdings Limited' ,
'BLIINK SAS' ,
'Blis Media Limited' ,
'Blue' ,
'Blue Billywig BV' ,
'Bmind a Sales Maker Company, S.L.' ,
'Bombora Inc.' ,
'Bounce Exchange, Inc.' ,
'Brand Metrics Sweden AB' ,
'Browsi Mobile Ltd.' ,
'Bucksense Inc.' ,
'BusinessClick' ,
'Cablato Limited' ,
'Capitaldata' ,
'Captify Technologies Limited' ,
'Cavai AS & UK' ,
'Cedato Technologies Ltd.' ,
'Celtra, Inc.' ,
'Centro, Inc.' ,
'CerebroAd.com s.r.o.' ,
'ChannelSight' ,
'Chargeads' ,
'Cheq AI Technologies Ltd.' ,
'Clicksco Digital Limited' ,
'Clipcentric, Inc.' ,
'Cloud Technologies S.A.' ,
'Codewise Sp. z o.o. Sp. k' ,
'Collective Europe Ltd.' ,
'Collective, Inc. dba Visto' ,
'Colpirio.com' ,
'Comcast International France SAS' ,
'Commanders Act' ,
'communicationAds GmbH & Co. KG' ,
'comScore, Inc.' ,
'Confiant Inc.' ,
'Connatix Native Exchange Inc.' ,
'ConnectAd Realtime GmbH' ,
'Consumable, Inc.' ,
'Contact Impact GmbH' ,
'Converge-Digital' ,
'Conversant Europe Ltd.' ,
'Crimtan Holdings Limited' ,
'Criteo SA' ,
'Cuebiq Inc.' ,
'Cxense ASA' ,
'Cybba, Inc.' ,
'Cydersoft' ,
'Czech Publisher Exchange z.s.p.o.' ,
'D-Edge' ,
'Dailymotion SA' ,
'Dataseat Ltd.' ,
'Dataxu, Inc.' ,
'DeepIntent, Inc.' ,
'DEFINE MEDIA GMBH' ,
'Delta Projects AB' ,
'Demandbase, Inc.' ,
'Densou Trading Desk ApS' ,
'Dentsu Aegis Network Italia SpA' ,
'Digilant Spain, SLU' ,
'Digital Control GmbH & Co. KG' ,
'Digital East GmbH' ,
'digitalAudience' ,
'DIGITEKA Technologies' ,
'Digitize New Media Ltd.' ,
'DigiTrust / IAB Tech Lab' ,
'district m inc.' ,
'DoubleVerify Inc.​' ,
'Dr. Banner' ,
'Drawbridge, Inc.' ,
'Dugout Limited' ,
'dunnhumby Germany GmbH' ,
'Duplo Media AS' ,
'Duration Media, LLC.' ,
'DynAdmic' ,
'Dynamic 1001 GmbH' ,
'EASYmedia GmbH' ,
'Effiliation' ,
'Effinity' ,
'Emerse Sverige AB' ,
'emetriq GmbH' ,
'EMX Digital LLC' ,
'Etarget SE' ,
'Eulerian Technologies' ,
'Exactag GmbH' ,
'Exponential Interactive, Inc.' ,
'Eyeota Ptd Ltd.' ,
'Ezoic Inc.' ,
'Fidelity Media' ,
'Fidzup' ,
'Fifty Technology Limited' ,
'Flashtalking, Inc.' ,
'FlexOffers.com, LLC' ,
'Forensiq LLC' ,
'FORTVISION' ,
'Free Stream Media Corp. dba Samba TV' ,
'Fusio by S4M' ,
'Fyber' ,
'Gamned' ,
'Gamoshi Ltd.' ,
'GDMServices, Inc. d/b/a FiksuDSP' ,
'Gemius SA' ,
'Genius Sports Media Limited' ,
'Getintent USA, inc.' ,
'GlobalWebIndex' ,
'Go.pl sp. z o.o.' ,
'Goldbach Group AG' ,
'Golden Bees' ,
'Goodway Group, Inc.' ,
'GP One GmbH' ,
'GRAPHINIUM' ,
'Greenhouse Group BV (with its trademark LemonPI)' ,
'GroupM UK Limited' ,
'GumGum, Inc.' ,
'Haensel AMS GmbH' ,
'Happydemics' ,
'hbfsTech' ,
'HIRO Media Ltd.' ,
'Hivestack Inc.' ,
'Hottraffic BV (DMA Institute)' ,
'Hybrid Adtech GmbH' ,
'ID5 Technology SAS' ,
'IgnitionAi Ltd.' ,
'IgnitionOne' ,
'Illuma Technology Limited' ,
'Impactify' ,
'Impression Desk Technologies Limited' ,
'Improve Digital International BV' ,
'Index Exchange, Inc.' ,
'INFINIA MOBILE S.L.' ,
'InMobi Pte Ltd.' ,
'INNITY' ,
'Innovid Inc.' ,
'Inskin Media Ltd.' ,
'Inspired Mobile Limited' ,
'Instinctive, Inc.' ,
'Instreamatic inc.' ,
'InsurAds Technologies SA.' ,
'Integral Ad Science, Inc.' ,
'Intent Media, Inc.' ,
'Intercept Interactive Inc. dba Undertone' ,
'Internet BillBoard a.s.' ,
'Intowow Innovation Ltd.' ,
'INVIBES GROUP' ,
'iotec global Ltd.' ,
'IPONWEB GmbH' ,
'Jaduda GmbH' ,
'Jampp Ltd.' ,
'Jivox Corporation' ,
'Join' ,
'Jointag S.r.l.' ,
'Justpremium BV' ,
'Kairos Fire' ,
'Kayzen' ,
'Keymantics' ,
'Knorex Pte Ltd.' ,
'Kochava Inc.' ,
'KUPONA GmbH' ,
'Kwanko' ,
'LBC France' ,
'Leadplace - Temelio' ,
'LeftsnRight, Inc. dba LIQWID' ,
'Leiki Ltd.' ,
'LEMO MEDIA GROUP LIMITED' ,
'Lifesight Pte. Ltd.' ,
'LifeStreet Corporation' ,
'Liftoff Mobile, Inc.' ,
'Ligatus GmbH' ,
'Linicom' ,
'LiquidM Technology GmbH' ,
'Little Big Data sp.z.o.o.' ,
'Liveintent Inc.' ,
'LiveRamp, Inc.' ,
'LKQD, a division of Nexstar Digital, LLC.' ,
'Localsensor B.V.' ,
'Location Sciences AI Ltd.' ,
'LoopMe Ltd.' ,
'LotaData, Inc.' ,
'Lotame Solutions, Inc.' ,
'Lucid Holdings, LLC' ,
'M32 Connect Inc.' ,
'Madington' ,
'Madison Logic, Inc.' ,
'Madvertise Media' ,
'mainADV Srl' ,
'MAIRDUMONT NETLETIX GmbH & Co. KG' ,
'Marfeel Solutions S.L' ,
'Market Resource Partners LLC' ,
'Maximus Live LLC' ,
'Maytrics GmbH' ,
'mbr targeting GmbH' ,
'McCann Discipline Ltd.' ,
'Media.net Advertising FZ-LLC' ,
'Mediaforce Ltd.' ,
'MediaMath, Inc.' ,
'mediarithmics SAS' ,
'Mediasmart Mobile S.L.' ,
'Meetrics GmbH' ,
'MGID Inc.' ,
'Mindlytix SAS' ,
'MiQ' ,
'Mirando GmbH & Co KG' ,
'MISSENA' ,
'mobalo GmbH' ,
'Mobfox US LLC' ,
'Mobile Journey B.V.' ,
'Mobile Professionals BV' ,
'Mobilewalla, Inc.' ,
'Mobsuccess' ,
'Mobusi Mobile Advertising S.L.' ,
'My6sense Inc.' ,
'Myntelligence Limited' ,
'MyTraffic' ,
'N Technologies Inc.' ,
'Nano Interactive GmbH' ,
'Nativo, Inc.' ,
'Near Pte Ltd.' ,
'Neodata Group srl' ,
'NEORY GmbH' ,
'Netsprint SA' ,
'NetSuccess, s.r.o.' ,
'netzeffekt GmbH' ,
'NEURAL.ONE' ,
'Neustar on behalf of The Procter & Gamble Company' ,
'Neustar, Inc.' ,
'News and Media Holding, a.s.' ,
'NEXD' ,
'NextRoll, Inc.' ,
'Nielsen Marketing Cloud' ,
'Norstat Danmark A/S' ,
'Noster Finance S.L.' ,
'Notify' ,
'nugg.ad GmbH' ,
'numberly' ,
'Oath (EMEA) Limited' ,
'Ogury Ltd.' ,
'On Device Research Limited' ,
'OnAudience Ltd.' ,
'OneTag Ltd.' ,
'Onfocus (Adagio)' ,
'Online Advertising Network Sp. z.o.o.' ,
'Online Solution Int Limited' ,
'Onnetwork Sp. z.o.o.' ,
'Ooyala Inc.' ,
'OpenX' ,
'Opinary GmbH' ,
'Optomaton UG' ,
'Oracle' ,
'Oracle AddThis' ,
'Orion Semantics' ,
'ORTEC B.V.' ,
'Otto (GmbH & Co KG)' ,
'Outbrain UK Ltd.' ,
'PaperG, Inc. dba Thunder Industries' ,
'Parsec Media Inc.' ,
'Passendo ApS' ,
'Perform Media Services Ltd.' ,
'Permodo GmbH' ,
'Permutive Ltd.' ,
'Permutive Technologies, Inc.' ,
'Pexi B.V.' ,
'pilotx.tv' ,
'Pixalate, Inc.' ,
'PIXIMEDIA SAS' ,
'Platform161' ,
'Playbuzz Ltd.' ,
'Playground XYZ EMEA Ltd.' ,
'plista GmbH' ,
'Pocketmath Pte Ltd.' ,
'Polar Mobile Group Inc.' ,
'PowerLinks Media Limited' ,
'Predicio' ,
'PREX Programmatic Exchange GmbH & Co KG' ,
'Programatica de publicidad S.L.' ,
'Proxi.cloud Sp. z o.o.' ,
'PROXISTORE' ,
'PUB OCEAN LIMITED' ,
'Publicis Media GmbH' ,
'Publishers Internationale Pty Ltd.' ,
'PubMatic, Inc.' ,
'PubNative GmbH' ,
'PulsePoint, Inc.' ,
'Purch Group, Inc.' ,
'PurposeLab, LLC' ,
'Qriously' ,
'Quantcast International Limited' ,
'Qwertize' ,
'R-Advertising' ,
'R-TARGET' ,
'Radio Net Media Limited' ,
'Rakuten Marketing LLC' ,
'Readpeak Oy' ,
'Realeyes OÜ' ,
'realzeit GmbH' ,
'ReigNN Platform Ltd.' ,
'Relay42 Netherlands B.V.' ,
'remerge GmbH' ,
'Research and Analysis of Media in Sweden AB' ,
'Research Now Group, Inc.' ,
'Revcontent, LLC' ,
'Reveal Mobile, Inc.' ,
'RevLifter Ltd.' ,
'Rezonence Limited' ,
'RhythmOne, LLC' ,
'Rich Audience' ,
'RMSi Radio Marketing Service interactive GmbH' ,
'Rockabox Media Ltd.' ,
'Rockerbox, Inc.' ,
'RockYou, Inc.' ,
'Roq.ad GmbH' ,
'RTB House S.A.' ,
'RTK.IO, Inc.' ,
'RUN, Inc.' ,
'salesforce.com, inc.' ,
'Samba TV UK Limited' ,
'Sanoma Media Finland' ,
'Scene Stealer Limited' ,
'Schibsted Norge AS' ,
'Schibsted Product and Tech UK' ,
'Seeding Alliance GmbH' ,
'Seedtag Advertising S.L' ,
'Seenthis AB' ,
'Sellpoints Inc.' ,
'Semasio GmbH' ,
'Seznam.cz, a.s.' ,
'ShareThis, Inc.' ,
'Sharethrough, Inc.' ,
'SheMedia, LLC' ,
'Shopalyst Inc.' ,
'Shopstyle' ,
'ShowHeroes GmbH' ,
'Sift Media, Inc.' ,
'Signal Digital Inc.' ,
'Signals' ,
'Simplifi Holdings Inc.' ,
'SINGLESPOT SAS' ,
'Sirdata' ,
'Sizmek' ,
'Skaze' ,
'Skimbit Ltd.' ,
'SlimCut Media SAS' ,
'Smaato, Inc.' ,
'Smadex SL' ,
'Smart Adserver' ,
'Smart Traffik' ,
'smartclip Europe GmbH' ,
'Smartclip Hispania SL' ,
'Smartme Analytics' ,
'Smartology Limited' ,
'SMARTSTREAM.TV GmbH' ,
'SmartyAds Inc.' ,
'Smile Wanted Group' ,
'Snapsort Inc., operating as Sortable' ,
'Social Tokens Ltd.' ,
'Sojern, Inc.' ,
'Solocal' ,
'Somo Audience Corp' ,
'Sonobi, Inc.' ,
'Soundcast' ,
'Sourcepoint Technologies, Inc.' ,
'Sovrn Holdings Inc.' ,
'Spolecznosci Sp. z.o.o. Sp. k.' ,
'Sportradar AG' ,
'Spot.IM Ltd.' ,
'Spotad' ,
'SpotX' ,
'SpringServe, LLC' ,
'StackAdapt' ,
'StartApp Inc.' ,
'Steel House, Inc.' ,
'Ströer Mobile Performance GmbH' ,
'Ströer SSP GmbH' ,
'Sub2 Technologies Ltd.' ,
'Sublime' ,
'SunMedia' ,
'Switch Concepts Limited' ,
'SYNC' ,
'TabMo SAS' ,
'Taboola Europe Limited' ,
'TACTIC™ Real-Time Marketing AS' ,
'Tapad, Inc.' ,
'Tapjoy, Inc.' ,
'TAPTAP Networks SL' ,
'Targetspot Belgium SPRL' ,
'Teads' ,
'Tealium Inc.' ,
'Teemo SA' ,
'Telaria, Inc.' ,
'Telecoming S.A.' ,
'Telefonica Investigación y Desarrollo S.A.U' ,
'Teroa S.A.' ,
'The ADEX GmbH' ,
'The Kantar Group Limited' ,
'The MediaGrid Inc.' ,
'The Ozone Project Limited' ,
'The Reach Group GmbH' ,
'The Rubicon Project, Inc.' ,
'The Trade Desk' ,
'Think Clever Media' ,
'Thirdpresence Oy' ,
'Timehop, Inc.' ,
'TimeOne' ,
'Totaljobs Group Ltd.' ,
'Tradedoubler AB' ,
'Tradelab, SAS' ,
'TradeTracker' ,
'travel audience GmbH' ,
'TreSensa, Inc.' ,
'Triapodi Ltd.' ,
'Triboo Data Analytics' ,
'TripleLift, Inc.' ,
'Triton Digital Canada Inc.' ,
'TrueData Solutions, Inc.' ,
'TTNET AS' ,
'Tunnl BV' ,
'Turbo' ,
'twiago GmbH' ,
'UberMedia, Inc.' ,
'ucfunnel Co., Ltd.' ,
'Underdog Media LLC' ,
'Unruly Group Ltd.' ,
'uppr GmbH' ,
'Uprival LLC' ,
'usemax advertisement (Emego GmbH)' ,
'Vdopia DBA Chocolate Platform' ,
'Ve Global' ,
'VECTAURY' ,
'Venatus Media Limited' ,
'Vibrant Media Limited' ,
'video intelligence AG' ,
'Video Media Groep B.V.' ,
'Video Reach' ,
'Vidoomy Media SL' ,
'ViewPay' ,
'Viralize SRL' ,
'Visarity Technologies GmbH' ,
'VRTCAL Markets, Inc.' ,
'Vuble' ,
'WebAds B.V' ,
'Webedia' ,
'WebMediaRM' ,
'WEBORAMA' ,
'Welect GmbH' ,
'WhatRocks Inc.' ,
'Whenever Media Ltd.' ,
'White Ops, Inc.' ,
'Widespace AB' ,
'Wizaly' ,
'X-Mode Social, Inc.' ,
'xAd, Inc. dba GroundTruth' ,
'YellowHammer Media Group' ,
'Yieldlab AG' ,
'Yieldlove GmbH' ,
'Yieldmo, Inc.' ,
'Yieldr UK' ,
'YOC AG' ,
'Yormedia Solutions Ltd.' ,
'ZBO Media' ,
'Zemanta, Inc.' ,
'zeotap GmbH' ,
'Zeta Global' ,
'Ziff Davis LLC' ,
'ZighZag' ,
'Non-TCF Registered Vendors' ,
'1&1 Internet' ,
'1000mercis' ,
'1000mercis' ,
'12 Digit Marketing' ,
'12DigitMedia' ,
'12DigitMedia' ,
'161Media' ,
'161Media' ,
'1DMP' ,
'1plusX' ,
'33Across (fka Tynt Multimedia)' ,
'4Finance' ,
'4INFO' ,
'4w Marketplace' ,
'A9' ,
'AB Tasty' ,
'Accordant Media' ,
'Accuen Media' ,
'actionpay' ,
'ActionX' ,
'Active Agent' ,
'activecore' ,
'Acuity Ads' ,
'Acxiom' ,
'AD EBiS' ,
'Ad Maven' ,
'ad pepper media' ,
'Ad River' ,
'Ad4Game' ,
'ad4mat' ,
'ad:C media' ,
'Adacado' ,
'Adadyn (formerly Ozone Media)' ,
'Adality' ,
'ADARA Analytics' ,
'Adblade' ,
'adbooth Media Group' ,
'Adbrain' ,
'AdClear' ,
'AdCompass' ,
'Addaptive (Formerly DataPoint Media)' ,
'Addition+' ,
'AddThis' ,
'Adelphic' ,
'Adelphic Mobile' ,
'Adform' ,
'AdFox' ,
'AdGear' ,
'AdInte' ,
'AdJug' ,
'adjust' ,
'AdKarma' ,
'adKernel' ,
'AdLantic Online Advertising' ,
'ADMAN' ,
'AdMaster (Jing Shuo Technology)' ,
'AdMaxim' ,
'AdMaxim Inc.' ,
'Admedo' ,
'AdMetrics Media' ,
'ADMIXER' ,
'ADMIZED' ,
'Admo.TV' ,
'AdMob (Google)' ,
'Admotion' ,
'Adnet' ,
'adNET.de' ,
'Adobe' ,
'Adobe (Omniture)' ,
'Adobe Creative Cloud (Typekit)' ,
'Adobe Marketing Cloud (Analytics)' ,
'Adobe Marketing Cloud (Analytics) Formerly Site Catalyst HBX' ,
'Adobe Marketing Cloud (Audience Manager)' ,
'Adobe Marketing Cloud (Target)' ,
'Adobe Marketing Cloud (Target)' ,
'AdOcean' ,
'Adotmob' ,
'AdoTube' ,
'Adperium' ,
'AdPilot' ,
'ADPLUS' ,
'AdPredictive' ,
'AdReady' ,
'Adroit Digital' ,
'AdRoll' ,
'Adroute' ,
'AdSame' ,
'Adscience' ,
'AdServerPub' ,
'ADSKOM' ,
'Adslot' ,
'AdSpeed' ,
'AdSpirit' ,
'AdStract' ,
'AdsWizz' ,
'Adtarget.me' ,
'Adtelligence' ,
'AdTheorent' ,
'AdTiger' ,
'Advertising.com' ,
'AdvertPro' ,
'adwebster' ,
'AdYapper' ,
'adyard' ,
'Adyoulike' ,
'Affectv' ,
'Affilinet GmbH' ,
'Affiperf' ,
'AiData' ,
'Akamai' ,
'AkaNe' ,
'ALC' ,
'Alenty' ,
'Amazon' ,
'Amazon Ad System' ,
'Amazon Ad System UK' ,
'Amazon Associates' ,
'Amazon Web Services' ,
'Amazon Web Services, Inc (“AWS”)' ,
'AMoAd' ,
'Amobee' ,
'Amobee (Formally Adconion Media Group)' ,
'Ampush' ,
'Annalect' ,
'Anonymousdmp' ,
'AOL Advertising' ,
'AOL Behavioral Advertising (Tacoda)' ,
'Appier' ,
'AppNexus' ,
'appTV' ,
'AppVador' ,
'APT from Yahoo!' ,
'Arbor (formerly pippio)' ,
'Arrivalist' ,
'Artefact (Formerly NetBooster Group)' ,
'Artificial Computation Intelligence' ,
'Assembly (formerly TargetCast)' ,
'Associated Newspapers Ltd. (MailOnline, ThisIsMoney & Metro)' ,
'AT Internet' ,
'AT&T Adobe Cloud Marketing' ,
'AT&T AdWorks' ,
'Atedra' ,
'ATG Commerce' ,
'Audience Ad Network (Adnamic)' ,
'Audience Network (Previously LiveRail)' ,
'Audience2Media' ,
'AudienceInsights' ,
'AudienceScience' ,
'AudienceTV' ,
'Auditorius' ,
'Avazu Network' ,
'Avocet' ,
'Baidu' ,
'BannerConnect' ,
'Bannerflow' ,
'Bazaarvoice' ,
'Be On (formerly Goviral)' ,
'Beeswax' ,
'Begun' ,
'Bidswitch' ,
'BidTellect' ,
'BidTheatre' ,
'Big Data Exchange' ,
'BIG Exchange' ,
'Bilin' ,
'Bisnode (formerly Esendra)' ,
'bitly' ,
'Blinkx' ,
'BlueConic' ,
'Bombora' ,
'Bowen Craggs' ,
'Bradford Exchange' ,
'BrainPad' ,
'BrandCrumb' ,
'BridgeTrack' ,
'Bridgewell (Scupio)' ,
'BrightRoll' ,
'Bypass' ,
'C3 Metrics' ,
'Captify' ,
'Capturly' ,
'Carhartt' ,
'Catalina Marketing' ,
'CBS Interactive' ,
'CDK Digital Marketing' ,
'CentralTag' ,
'Centro' ,
'Centrois' ,
'CG13' ,
'Chamaleon' ,
'Chitika' ,
'Choozle' ,
'CJ Affiliate by Conversant (formerly Commission Junction)' ,
'Clearstream.TV' ,
'Clickagy' ,
'Clickpoint' ,
'ClickTale' ,
'CNET' ,
'CoAdvertise' ,
'Cognitiv' ,
'Cognitive Match' ,
'CogoCast' ,
'Collective' ,
'Collective Europe' ,
'Collective UK' ,
'Collider Media' ,
'comScore' ,
'ConnectAd' ,
'Connected Interactive' ,
'Connexity' ,
'Constant Contact' ,
'Content Spread' ,
'Content Square' ,
'Converge Digital' ,
'Conversant' ,
'ConversionRuler' ,
'Convert' ,
'Convert Insights (formerly Reedge)' ,
'ConvertMedia (formerly Contextin)' ,
'CookieQ (Baycloud Systems)' ,
'Core Audience (formerly Red Aril)' ,
'CPMStar' ,
'CPXi' ,
'Crashlytics' ,
'Crate & Barrel' ,
'Creafi' ,
'Crimtan' ,
'Crisp Media' ,
'Criteo' ,
'CRM4D' ,
'Cross Listing' ,
'Cross Pixel' ,
'Crowd Science' ,
'CTS Eventim ES' ,
'CTS Eventim FR' ,
'Cubed' ,
'Cup Interactive' ,
'Cxense' ,
'D4t4 (formerly Celebrus)' ,
'DAC (D.A.Consortium)' ,
'DataLab USA' ,
'Datalogix' ,
'DataMind' ,
'Dataxpand' ,
'DataXu' ,
'Datonics' ,
'DaVinci II (FKA Gravity4)' ,
'DC Storm' ,
'Dedicated Media' ,
'Deep Intent' ,
'Defy Media (formerly Break Media)' ,
'Delta Projects' ,
'Demandbase' ,
'Deqwas' ,
'Didit' ,
'Digitize' ,
'DigiTrust' ,
'DirectREV' ,
'Disqus' ,
'District M' ,
'Division-D' ,
'Divisiond (formerly 3 Interactive)' ,
'DMA Institute (formerly HotTraffic)' ,
'DotAndMedia' ,
'Dotomi' ,
'DoubleClick' ,
'DoubleClick Bid Manager (formerly Invite Media)' ,
'Drawbridge' ,
'Dstillery (formerly Media6Degrees)' ,
'DTscout' ,
'DuMedia' ,
'DynAd' ,
'Dynamic Yield' ,
'e-planning' ,
'EastBay' ,
'EASYmedia GmbH (formerly Rivity)' ,
'eBay' ,
'ECONA' ,
'Econda' ,
'Eduscho (Tchibo)' ,
'Effective Measure' ,
'eHealthcare Solutions' ,
'Eloqua (Oracle Marketing Cloud)' ,
'EMC' ,
'Emediate' ,
'emetriq' ,
'Engage BDR' ,
'engage:BDR (Blink New Media)' ,
'Engine Media' ,
'Eniro' ,
'Ensemble' ,
'Epom' ,
'eTracker' ,
'etracker GmbH' ,
'Exactag (formerly Falk Multichannel)' ,
'eXelate' ,
'Experian Marketing Services' ,
'Exponential Interactive' ,
'Extreme Reach' ,
'Eyeota' ,
'eyereturn marketing' ,
'Eyeview' ,
'Ezakus (aquired by NP6)' ,
'Fabric' ,
'Facebook' ,
'Facebook Business (formerly Facebook Custom Audience)' ,
'Facebook for Developers (formerly Facebook Connect)' ,
'Facebook Social Graph' ,
'Facebook Social Plugins' ,
'FACETZ (DCA)' ,
'Facilitate Digital' ,
'Fast G8' ,
'Fiksu' ,
'Firefly Video' ,
'Flashtalking' ,
'Fluct' ,
'Flurry' ,
'FlxOne' ,
'fnac' ,
'FNAC Spectacles' ,
'Fonecta' ,
'Fonecta.fi' ,
'Fraud Logix' ,
'FreakOut' ,
'Freebit (AdMind)' ,
'FreeWheel' ,
'Fringe81' ,
'Full Circle Studies' ,
'Full Tango' ,
'fullstory' ,
'G4 Native (formerly Triggit)' ,
'Gamespot' ,
'Gamut (formerly Cox Digital Solutions)' ,
'Gazprom-Media Digital' ,
'Geenie' ,
'GetIntent' ,
'Giant Media' ,
'Gigya' ,
'Gilt' ,
'Global Web Index' ,
'Google Ad Services' ,
'Google AdSense' ,
'Google AdWords' ,
'Google Analytics' ,
'Google Attribution 360 (formerly Adometry)' ,
'Google Display Network' ,
'Google Inc.' ,
'Google Translate' ,
'Graphinium' ,
'Gravity' ,
'Green & Red Technologies' ,
'GroovinAds' ,
'GroundTruth' ,
'Groupon' ,
'GSI Media Network' ,
'GumGum' ,
'Gunosy' ,
'Hanna Andersson' ,
'Harren Media' ,
'Healthy Offers Inc.' ,
'Heatmap' ,
'Hipcricket (formerly Augme Technologies)' ,
'HIRO Media' ,
'Histats' ,
'HockeyApp' ,
'Hotjar' ,
'HOTWords' ,
'Hupso' ,
'i-Behavior' ,
'i-mobile' ,
'iBILLBOARD (formerly BBelements)' ,
'IBM' ,
'iClick Interactive' ,
'iCrossing' ,
'Imfernsehen GmbH' ,
'IMM' ,
'Impression Desk' ,
'Improve Digital' ,
'Indeed' ,
'Index Exchange' ,
'Index Exchange (Formerly Casale Media)' ,
'Index Exchange by Casale Media' ,
'IndustryBrains' ,
'Infectious Media' ,
'Inflection Point Media' ,
'INFOnline' ,
'InMobi' ,
'Innovid' ,
'InSkin Media' ,
'Instinctive' ,
'intelliAd' ,
'Intelligent Reach' ,
'Intent IQ' ,
'Intent Media' ,
'InterMundo Media' ,
'Intimate Merger' ,
'Inuvo (formerly NetSeer)' ,
'Invoca' ,
'Iotec' ,
'iotec global Ltd.' ,
'IPONWEB' ,
'Iprom' ,
'iPromote' ,
'iSocket' ,
'iSpot.TV' ,
'IXI Services' ,
'Jetpack Digital' ,
'Jivox' ,
'JSE Coin' ,
'Jumplead' ,
'Just Uno' ,
'Kadam Online Advertising Service' ,
'Kameleoon' ,
'Kargo' ,
'Kavanga' ,
'KBM Group' ,
'Keyade' ,
'Kissmetrics' ,
'Knorex' ,
'Knotch' ,
'Kontera Technologies' ,
'Kortx' ,
'Kwanko' ,
'Kyocera Communication Systems Co. (Kanade)' ,
'L2Mixer' ,
'Lagardere Publicite' ,
'LagardÃ¨re Advertising' ,
'Lands End' ,
'LCX Digital' ,
'Leading Reports' ,
'LeadInspector' ,
'Leiki' ,
'LifeStreet Corporation' ,
'LifeStreet Media' ,
'Ligatus' ,
'Light Reaction' ,
'Limk' ,
'Limk' ,
'LinkedIn' ,
'LinkedIn Marketing Solutions' ,
'Linkwise' ,
'LiveIntent' ,
'LiveRamp' ,
'LKQD' ,
'Lodeo.io' ,
'Logicad' ,
'logly' ,
'Longboard Media' ,
'Lotame' ,
'Lotame (Previously AdMobius)' ,
'Luc.id' ,
'LucidMedia' ,
'Lucky Orange' ,
'm-pathy' ,
'M. P. New Media GmbH' ,
'Macromill' ,
'Madison Logic' ,
'MADNET' ,
'Magnetic' ,
'Magnetic (Formally MyBuys)' ,
'mainADV (MainAd)' ,
'Maist' ,
'Mapp' ,
'Marchex' ,
'Marin Software' ,
'Market Ruler' ,
'Marketgid RU' ,
'MarketGid USA' ,
'Marketshare' ,
'Markit on Demand' ,
'MASTER TMS' ,
'Mastercard' ,
'Masterpass by Mastercard' ,
'Match.com' ,
'Matomo (Formerly PiWiK Analytics)' ,
'Matomy Media Ltd.' ,
'Maverick' ,
'MaxPoint Interactive' ,
'Maxymiser' ,
'mbr targeting' ,
'MBuy (formerly AdBuyer)' ,
'Media Group One (formerly Vertical Network)' ,
'Media Innovation Group' ,
'Media IQ' ,
'Media IQ Trace' ,
'Media Network ADLABS' ,
'media.net' ,
'MediaCrossing' ,
'Mediaglu (formerly MLN Advertising)' ,
'MediaMath' ,
'Mediaocean' ,
'mediaplex' ,
'MediaPost Communications' ,
'Mediarithmics' ,
'mediascale' ,
'Mediative' ,
'MediaWallah' ,
'Merkle' ,
'Meta Network' ,
'Metapeople' ,
'MeteoGroup' ,
'Meteora' ,
'Miaozhen' ,
'Miaozhen Systems' ,
'MicroAd' ,
'Microsoft' ,
'Microsoft Advertising' ,
'Microsoft Advertising Exchange (formerly AdECN)' ,
'Microsoft Bing Ads (formerly Microsoft adCenter)' ,
'Microsoft Media Network' ,
'Millenial Media (Jumptap)' ,
'Mixcloud' ,
'Mixpanel' ,
'Mixpo' ,
'mobile.de GmbH' ,
'Mogo Interactive' ,
'Moguldom' ,
'Mouseflow' ,
'MouseStats' ,
'mPlatform' ,
'MSN (Microsoft)' ,
'MTBurn' ,
'Nanigans' ,
'Nano Interactive' ,
'Narrative.io' ,
'Navegg' ,
'NDN' ,
'nend' ,
'Neodata' ,
'Neory (formerly Target Performance)' ,
'Net Avenir' ,
'NetAffiliation' ,
'Netbiscuits' ,
'Netmining' ,
'Neustar' ,
'Neustar AdAdvisor' ,
'Neustar Information Services' ,
'Neustar PlatformOne' ,
'News IQ' ,
'nex8' ,
'Nextag' ,
'Nextperf' ,
'Nielsen' ,
'Nielsen (formerly NetRatings SiteCensus)' ,
'Nielsen (formerly NetRatings)' ,
'NinthDecimal (formerly JiWire)' ,
'NTT DoCoMo' ,
'Nugg.ad' ,
'OK Cupid' ,
'One by AOL (formerly AOL ADTECH)' ,
'OneSpot' ,
'OneTrust Cookie Compliance (Optanon)' ,
'Onlysix Limited' ,
'OpenX Lift (formerly LiftDNA)' ,
'Optimatic' ,
'Optimax Media Delivery' ,
'Optimise Media' ,
'Optimizely' ,
'Optimum Response' ,
'Oracle Corporation' ,
'Oracle Data Cloud' ,
'Outbrain' ,
'OwnerIQ' ,
'OxaMedia' ,
'Pardot' ,
'Parrable' ,
'Parse.ly' ,
'Parsley' ,
'Peer39' ,
'Perfect Audience' ,
'Perfect Market' ,
'Performance Media' ,
'Photobucket' ,
'Phunware (formerly TapIt!)' ,
'Pinterest' ,
'Piximedia' ,
'Placed' ,
'Platform One (yieldone)' ,
'Plista' ,
'PLYmedia' ,
'Pocket (formerly Read It Later)' ,
'popIn' ,
'PowerLinks' ,
'Proclivity Media' ,
'Programmatic Mechanics' ,
'Proofpoint' ,
'Propeller Ads' ,
'Pt engine' ,
'Public-Idees' ,
'Publicis Groupe' ,
'Publy' ,
'PubMatic' ,
'Pulpo Media' ,
'Pulsepoint Ad Exchange' ,
'Pulsepoint Audience' ,
'Purch Group, Inc.' ,
'PushSpring' ,
'Qualia (fka BlueCava)' ,
'Quantcast' ,
'QuarticON' ,
'Rackspace' ,
'RadiumOne' ,
'Rakuten Display (formerly Rakuten MediaForge)' ,
'Rakuten Group' ,
'Reactful' ,
'Realmedia' ,
'Realytics' ,
'realzeit GmbH' ,
'ReAmp' ,
'Recruit Ad Network (Recruit Holdings, Inc.)' ,
'Recruitics' ,
'Reemo' ,
'Refined Labs' ,
'Relestar' ,
'Relestar (Relevad Corporation)' ,
'Republer' ,
'Resonate' ,
'Responsys' ,
'Retail 9 Ventures' ,
'ReTargeter' ,
'Retargetly' ,
'RevContent' ,
'Revee' ,
'RevJet' ,
'REVTRAX' ,
'REVV for Mobile (formerly Mobsmith)' ,
'RhythmOne' ,
'RichRelevance' ,
'RoadRunnerSports' ,
'Rockerbox' ,
'Rocket Fuel (formerly [x+1] xplusone)' ,
'Rollad' ,
'Rontar' ,
'Roq.ad' ,
'Roy Morgan Research' ,
'RSA' ,
'RTB House' ,
'Rtoaster' ,
'Rubicon Project' ,
'Rubicon Project (formerly FOX Audience Network)' ,
'RUN' ,
'Run Inc.' ,
'Rythm One' ,
'Safecount' ,
'Salesforce DMP' ,
'Salesforce DMP' ,
'SalesViewer' ,
'Sally Beauty' ,
'Satori' ,
'Say Media' ,
'ScaleOut' ,
'Scarab research' ,
'Scoota' ,
'Scorecard Research' ,
'SearchIgnite' ,
'SecuredVisit' ,
'Seeding Alliance' ,
'Seenergy Netherlands B.V.' ,
'Segmint' ,
'SekiNdo' ,
'Sellpoints' ,
'Semasio' ,
'Sephora FR' ,
'SET Media' ,
'Shareaholic' ,
'ShareThis' ,
'Sharethrough' ,
'ShinyStat' ,
'ShopBack' ,
'Shopzilla' ,
'Signal (formerly BrightTag)' ,
'Simpli.fi' ,
'Sirok' ,
'SiteScout' ,
'Sizmek' ,
'SK Media Group, LLC' ,
'SkimLinks' ,
'Skype' ,
'SlimCutMedia' ,
'Smart Leads' ,
'smartclip' ,
'SmartLook' ,
'Snoobi Oy' ,
'So-net Media Networks' ,
'Sociomantic Labs GmbH' ,
'Solve Media' ,
'Sonobi' ,
'Sophus3' ,
'sovrn (formerly Lijit Networks)' ,
'Specific Media' ,
'Speed Shift Media' ,
'Spongecell' ,
'Sport1' ,
'SpotXchange' ,
'Spree7' ,
'SpringServe (fka PubSquared)' ,
'SpringServe, LLC' ,
'Stailamedia AG' ,
'SteelHouse' ,
'Stirista' ,
'Storygize' ,
'Stroer (formerly adscale)' ,
'Struq' ,
'SubPLY' ,
'Suite 66' ,
'SundaySky' ,
'Supership' ,
'Survata' ,
'Swisscom' ,
'Switch Concepts' ,
'Symantec (Norton Secured Seal)' ,
'Taboola' ,
'Tag Commander' ,
'Taggify' ,
'TAGGY' ,
'TailTarget' ,
'Tanx' ,
'Tapad' ,
'Tapone' ,
'Tapstream' ,
'Teads' ,
'Tealium' ,
'Telemetry' ,
'Telstra Advertising Network' ,
'TEST Company First Party Cookie Opt' ,
'The ADEX' ,
'The Globe and Mail' ,
'The Reach Group (formely redvertisment)' ,
'ThinkGeek' ,
'THROTLE' ,
'Throtle Onboarding' ,
'top5meilleurssitesderencontre' ,
'Totaljobs Group Ltd.' ,
'Trackuity' ,
'TradeDoubler' ,
'Tradelab' ,
'Traffiliate' ,
'TrafMag' ,
'Traverse Data' ,
'Treepodia' ,
'Tremor Video' ,
'TrenDemon' ,
'Tribal Fusion' ,
'Triblio' ,
'TripleLift' ,
'True Value' ,
'TruEffect' ,
'Truoptik' ,
'TubeMogul' ,
'Tune MobileAppTracking' ,
'Turn Inc.' ,
'TurnSocial' ,
'Twiago' ,
'Twitter' ,
'Twyn' ,
'UberMedia' ,
'Ubimo' ,
'Uliza' ,
'Ulta' ,
'Undertone' ,
'Unicorn' ,
'Unilever' ,
'Unilever EU' ,
'Unilever Food Solutions' ,
'United Internet Media GmbH' ,
'Unruly' ,
'uppr GmbH' ,
'UpToLike' ,
'Usemax' ,
'UserReport' ,
'Valiton' ,
'Varick Media Management' ,
'Vdopia' ,
'VE Global (Formely GDM Digital)' ,
'Venatus Media' ,
'Veruta' ,
'Vi Digital' ,
'Viacom' ,
'Viant' ,
'Vibrant Media' ,
'Vidazoo' ,
'VideoAmp' ,
'Videology (formerly TidalTV)' ,
'Videology Ltd.' ,
'VigLink' ,
'Vindico Group' ,
'Virool' ,
'Visa' ,
'Visible Measures' ,
'Visual Website Optimizer (Wingify)' ,
'VisualDNA (Imagini Holdings)' ,
'Vizury' ,
'VoiceFive' ,
'Voxus' ,
'Vpon' ,
'Vserve' ,
'Vserve' ,
'WayFair' ,
'WebAntenna' ,
'Webbula' ,
'Webtrekk' ,
'Webtrends' ,
'whos.amung.us' ,
'Wider Planet' ,
'WiredMinds' ,
'WiseMedia' ,
'WyWy' ,
'Xaxis' ,
'XiTi' ,
'xplosion interactive' ,
'XPO Knorex' ,
'Xrost' ,
'Yahoo Ad Exchange' ,
'Yahoo!' ,
'Yahoo! Ad Network' ,
'Yahoo! Advertising Solutions' ,
'Yahoo! Japan' ,
'Yahoo! Web Analytics' ,
'YellowHammer' ,
'Yieldbot' ,
'Yieldlab' ,
'Yieldmo' ,
'YieldPro (formerly Ancora)' ,
'Yieldr (formerly YD Group B.V.)' ,
'YouTube' ,
'YuMe' ,
'YuMe' ,
'Zalando Adtech Lab' ,
'ZeBestOf' ,
'Zedo' ,
'Zemanta' ,
'Ziff Davis' ,
'Ziggo' ,
'Zipline DMP' ,
'Zucks' ,
'Zypmedia'
];
